<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
echo '</div>'; //* end .site-inner or #inner

do_action( 'genesis_before_footer' );

//do_action( 'genesis_footer' );


do_action( 'genesis_after_footer' );

echo '</div>'; //* end .site-container or #wrap
?>
	<div class="sponsors">
    	<div class="title">
        	<h2><?php _e('SPONSORED BY','tourofcrete');?></h2>
        </div>
    	<div class="content" align="center">
            <a href="http://www.cretansportscycling.gr/" target="_blank" alt="Cretan Sports Cycling">
               <img src="http://tourofcrete.com/wp-content/themes/tourofcrete/images/csc.png" title="Cretan Sports Cycling" border="0" />
            </a>
            <a href="http://fotomaris.gr/" target="_blank" alt="Foto Maris">
               <img src="http://tourofcrete.com/wp-content/themes/tourofcrete/images/fotomaris.png" title="Foto Maris" border="0" />
            </a>
            <a href="https://www.facebook.com/Delta-Carbon-Works-785460848159497" target="_blank" alt="Cyclomania" target="_blank" alt="Cyclomania">
               <img src="http://tourofcrete.com/wp-content/themes/tourofcrete/images/cyclomania.png" title="Cyclomania" border="0" />
            </a>
            <a href="http://www.minoan.gr/en/crete" target="_blank" alt="Minoan Lines">
               <img src="http://tourofcrete.com/wp-content/themes/tourofcrete/images/minoan.png" title="Minoan Lines" border="0" />
            </a>
            <a href="http://www.mbike.gr/" target="_blank" alt="MBike">
               <img src="http://tourofcrete.com/wp-content/themes/tourofcrete/images/mbike.png" title="MBike" border="0" />
            </a>
            <a href="http://www.hellenic-cycling.gr/" target="_blank" alt="ΕΟΠ">
               <img src="http://tourofcrete.com/wp-content/themes/tourofcrete/images/EOP.png" title="Hellenic Cycling Association" border="0" />
            </a>

        </div>
    </div>
<?php
do_action( 'genesis_after' );
wp_footer(); //* we need this for plugins
?>
</body>
</html>
